import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-[90%] md:max-w-[1550px] m-auto my-[10px]">
          <Header />
        </header>
        <main className="max-w-[1550px] m-auto">
          {children}
        </main>
        <footer className="max-w-[1550px] m-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
